"use strict";
const {requireAdmin,privateDb,savePrivateDb,clean,id,addNotification}=require("./_common");
const {ensure,balance}=require("../wallet/_common");
const {sendTelegram,escapeHtml}=require("../../telegram");
const {sendPushToUser}=require("../../push");
function normalizeMethods(input,fallback){
 if(!Array.isArray(input))return fallback;
 return input.map((x,i)=>({id:clean(x.id||`m${Date.now()}${i}`,40).toLowerCase().replace(/[^a-z0-9_-]/g,"-"),name:clean(x.name,60)||`Metode ${i+1}`,account:clean(x.account,100),holder:clean(x.holder,100),enabled:x.enabled!==false,automatic:x.automatic===true})).filter(x=>x.id&&x.name).slice(0,30);
}
module.exports=async(req,res)=>{if(!requireAdmin(req))return res.status(401).json({error:"Unauthorized"});try{const db=ensure(await privateDb());
 if(req.method==="GET")return res.json({success:true,settings:{minTopup:Number(db.walletSettings.minTopup||10000),minWithdraw:Number(db.walletSettings.minWithdraw||10000),feeWithdraw:Number(db.walletSettings.feeWithdraw||0),topupMethods:db.walletSettings.topupMethods,withdrawMethods:db.walletSettings.withdrawMethods},topups:db.topups.slice(0,200),withdrawals:db.withdrawals.slice(0,200),users:db.users.map(u=>({id:u.id,username:u.username,name:u.name,type:u.type,balance:balance(u)}))});
 const b=req.body||{},action=clean(b.action,30);
 if(action==="settings"){
  const topupFallback=db.walletSettings.topupMethods, withdrawFallback=db.walletSettings.withdrawMethods;
  db.walletSettings={minTopup:Math.max(1000,Number(b.minTopup)||10000),minWithdraw:Math.max(1000,Number(b.minWithdraw)||10000),feeWithdraw:Math.max(0,Number(b.feeWithdraw)||0),topupMethods:normalizeMethods(b.topupMethods,topupFallback),withdrawMethods:normalizeMethods(b.withdrawMethods,withdrawFallback)};
  await savePrivateDb(db);return res.json({success:true,settings:db.walletSettings});
 }
 const uid=clean(b.userId,100),u=db.users.find(x=>String(x.id)===String(uid));if(!u)return res.status(404).json({error:"Akun tidak ditemukan."});
 if(action==="approveTopup"){const t=db.topups.find(x=>String(x.id)===String(b.topupId)&&String(x.userId)===uid);if(!t||t.status!=="waiting_proof")return res.status(404).json({error:"Top up tidak ditemukan atau sudah diproses."});t.status="paid";t.paidAt=new Date().toISOString();const amount=Number(t.amount)||0;u.balance=balance(u)+amount;db.walletLedger.unshift({id:id("wl"),userId:u.id,type:"topup",amount,note:`Top up ${t.method}`,ref:t.id,createdAt:new Date().toISOString(),meta:{method:t.method}});addNotification(db,u.id,"Top up berhasil",`Saldo Rp${amount.toLocaleString("id-ID")} sudah ditambahkan admin.` ,"success");await savePrivateDb(db);await sendPushToUser(db,u.id,{title:"Top up berhasil",body:`Saldo Rp${amount.toLocaleString("id-ID")} sudah ditambahkan admin.`,data:{type:"topup",link:"akun.html#wallet"}});await sendTelegram(`✅ <b>TOP UP DISETUJUI</b>\n\n👤 ${escapeHtml(u.name||u.username)}\n💰 Rp${amount.toLocaleString("id-ID")}\n🧾 ${escapeHtml(t.id)}`).catch(()=>{});return res.json({success:true,balance:u.balance});}
 if(action==="rejectTopup"){const t=db.topups.find(x=>String(x.id)===String(b.topupId)&&String(x.userId)===uid);if(!t||t.status!=="waiting_proof")return res.status(404).json({error:"Top up tidak ditemukan atau sudah diproses."});t.status="rejected";t.adminNote=clean(b.note,300);addNotification(db,u.id,"Top up ditolak",t.adminNote||"Bukti pembayaran tidak valid.","error");await savePrivateDb(db);await sendPushToUser(db,u.id,{title:"Top up ditolak",body:t.adminNote||"Bukti pembayaran tidak valid.",data:{type:"topup",link:"akun.html#wallet"}});return res.json({success:true});}
 if(action==="approveWithdraw"){const w=db.withdrawals.find(x=>String(x.id)===String(b.withdrawalId)&&String(x.userId)===uid);if(!w||w.status!=="pending")return res.status(404).json({error:"Penarikan tidak ditemukan atau sudah diproses."});w.status="paid";w.paidAt=new Date().toISOString();w.adminNote=clean(b.note,300);addNotification(db,uid,"Penarikan berhasil",`Penarikan Rp${Number(w.amount).toLocaleString("id-ID")} telah dibayarkan admin.` ,"success");await savePrivateDb(db);await sendPushToUser(db,uid,{title:"Penarikan berhasil",body:`Penarikan Rp${Number(w.amount).toLocaleString("id-ID")} telah dibayarkan admin.`,data:{type:"withdrawal",link:"akun.html#wallet"}});await sendTelegram(`✅ <b>PENARIKAN DIBAYAR</b>\n\n👤 ${escapeHtml(u.name||u.username)}\n💰 Rp${Number(w.amount).toLocaleString("id-ID")}\n🏦 ${escapeHtml(w.method)}\n🧾 ${escapeHtml(w.id)}`).catch(()=>{});return res.json({success:true});}
 if(action==="rejectWithdraw"){const w=db.withdrawals.find(x=>String(x.id)===String(b.withdrawalId)&&String(x.userId)===uid);if(!w||w.status!=="pending")return res.status(404).json({error:"Penarikan tidak ditemukan atau sudah diproses."});w.status="rejected";w.adminNote=clean(b.note,300);const refund=Number(w.total)||0;u.balance=balance(u)+refund;db.walletLedger.unshift({id:id("wl"),userId:uid,type:"withdrawal_refund",amount:refund,note:`Refund penarikan ${w.id}`,ref:w.id,createdAt:new Date().toISOString()});addNotification(db,uid,"Penarikan ditolak",`Saldo Rp${refund.toLocaleString("id-ID")} dikembalikan.${w.adminNote?` Alasan: ${w.adminNote}`:""}`,"error");await savePrivateDb(db);await sendPushToUser(db,uid,{title:"Penarikan ditolak",body:`Saldo Rp${refund.toLocaleString("id-ID")} dikembalikan.${w.adminNote?` Alasan: ${w.adminNote}`:""}`,data:{type:"withdrawal",link:"akun.html#wallet"}});return res.json({success:true});}
 if(action==="adjustBalance"){const amount=Number(b.amount);if(!Number.isFinite(amount)||amount===0)return res.status(400).json({error:"Nominal harus bukan nol."});u.balance=balance(u)+amount;db.walletLedger.unshift({id:id("wl"),userId:uid,type:amount>0?"admin_credit":"admin_debit",amount,note:clean(b.note||"Penyesuaian saldo admin",300),ref:"admin",createdAt:new Date().toISOString()});addNotification(db,uid,"Saldo diperbarui admin",`${amount>0?"Saldo bertambah":"Saldo berkurang"} Rp${Math.abs(amount).toLocaleString("id-ID")}.`,`info`);await savePrivateDb(db);return res.json({success:true,balance:u.balance});}
 return res.status(400).json({error:"Action tidak dikenal."});
 }catch(e){console.error(e);return res.status(500).json({error:e.message||"Wallet admin error."});}};
